# إعدادات الـ Development
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringDemo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
logging.level.com.mohammed.demo=DEBUG
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379