# إعدادات الـ Production
spring.datasource.url=jdbc:postgresql://db:5432/SpringDemo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=false
logging.level.com.mohammed.demo=INFO