spring.application.name=demo
# بيخلي H2 تعمل الجداول تلقائياً
spring.jpa.hibernate.ddl-auto=update
# بيظهر الـ SQL في الـ Terminal عشان تشوف إيه اللي بيحصل
spring.jpa.show-sql=true
# # إعدادات H2 Console عشان تقدر تدخل عليها من المتصفح
# spring.h2.console.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringDemo
spring.datasource.username=postgres
spring.datasource.password=1234
# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
# مستوى الـ Logging العام
logging.level.root=INFO

# مستوى الـ Logging للـ Package بتاعك بس
logging.level.com.mohammed.demo=DEBUG

# حفظ الـ Logs في ملف
logging.file.name=logs/app.log
# الـ Profile الافتراضي
spring.profiles.active=dev
